# Generated by Django 5.1.2 on 2024-10-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_number', models.CharField(max_length=50, unique=True)),
                ('components_makeup', models.TextField(help_text='List all components used for tank makeup.')),
                ('temperature_min', models.FloatField()),
                ('temperature_max', models.FloatField()),
                ('uses_rectifier', models.BooleanField(default=False)),
                ('rectifier_number', models.CharField(blank=True, max_length=50, null=True)),
                ('time_immersion_min', models.FloatField(help_text='Minimum immersion time in minutes.')),
                ('time_immersion_max', models.FloatField(help_text='Maximum immersion time in minutes.')),
                ('test_required', models.CharField(blank=True, help_text='Specify test requirements, e.g., water break test.', max_length=100, null=True)),
                ('process_description', models.CharField(choices=[('cleaning', 'Cleaning'), ('pre_pen_etching', 'Pre-Pen Etching'), ('rinsing', 'Rinsing'), ('chrome_plating', 'Chrome Plating'), ('cad_plating', 'Cad Plating'), ('anodizing', 'Anodizing'), ('nickel_plating', 'Nickel Plating'), ('cad_strip', 'Cad Strip'), ('chrome_strip', 'Chrome Strip'), ('nickel_strip', 'Nickel Strip'), ('passivation', 'Passivation'), ('nital_etch', 'Nital Etch'), ('deoxidizing', 'Deoxidizing')], max_length=50)),
            ],
        ),
    ]
