# Generated by Django 5.1.2 on 2024-10-30 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rack', '0002_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='application_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
