# Generated by Django 5.1.2 on 2024-10-29 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('revision', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acceptance_criteria', models.TextField()),
                ('paragraph_section', models.CharField(max_length=50)),
                ('sampling_plan', models.CharField(max_length=50)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='standards.standard')),
            ],
        ),
    ]
