# Generated by Django 5.1.2 on 2024-10-29 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='class_field',
            field=models.CharField(default='I', max_length=50),
        ),
        migrations.AddField(
            model_name='standard',
            name='process',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standard',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
