# Generated by Django 5.1.2 on 2024-10-29 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0002_standard_class_field_standard_process_standard_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('work_instruction', models.URLField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='process_photos/')),
                ('tank_number', models.CharField(blank=True, max_length=50, null=True)),
                ('manual_step_number', models.CharField(blank=True, max_length=50, null=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('soak_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('operator_signoff', models.CharField(blank=True, max_length=100, null=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='standards.standard')),
            ],
        ),
    ]
