# Generated by Django 5.1.2 on 2024-11-28 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0006_remove_processstep_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='class_field',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='type',
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=50)),
                ('types', models.CharField(max_length=50)),
                ('option_one', models.CharField(max_length=50)),
                ('option_two', models.CharField(max_length=50)),
                ('option_three', models.CharField(max_length=50)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='standards.standard')),
            ],
        ),
    ]
