# Generated by Django 5.1.2 on 2024-11-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0008_remove_standard_process_standard_standard_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
